version: '3'

services:
  core:
    restart: always
    build:
      context: docker/core
      args:
        USER_ID: ${USER_ID}
        GROUP_ID: ${GROUP_ID}
        PHP_VERSION: ${PHP_VERSION}
        ENV: ${ENV}
    volumes:
      - ${PROJECT_PATH_CORE}:/var/www/project/core:cached
      - ${SYMFONY_LOG_PATH}:/var/www/project/var/logs:cached
      - ${COMPOSER_PATH}/cache:/var/www/.composer/cache:cached
      - ${CRON_LOG_PATH}:/var/log/cron:cached
    env_file: .env
    logging:
      options:
        max-size: "400m"
        max-file: "3"

  nginx:
    restart: always
    build:
      context: docker/nginx
      args:
        PROJECT_DOMAIN_CORE: ${PROJECT_DOMAIN_CORE}
        ENV: ${ENV}
    ports:
      - ${HOST_IP}:80:80
      - ${HOST_IP}:443:443
    volumes:
      - ${PROJECT_PATH_CORE}:/var/www/project/core:cached
      - ${NGINX_LOG_PATH}:/var/log/nginx
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      default:
        aliases:
          - ${PROJECT_DOMAIN_CORE}
    logging:
      options:
        max-size: "400m"
        max-file: "3"

  mongo:
    image: mongo:4.2
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    command: --quiet
    ports:
      - ${HOST_IP}:27017:27017
    volumes:
      - ./var/lib/mongo:/data/db
    logging:
      driver: none
      options:
        max-size: "400m"
        max-file: "3"

  wasm:
    restart: on-failure
    command: sh -c "wasm-pack build"
    build:
      context: docker/wasm
    volumes:
      - ${PROJECT_PATH_WASM}:/var/www/project/core/wasm:cached
      - ${RUST_LOG_PATH}:/var/log/rust:delegated
    logging:
      options:
        max-size: "400m"
        max-file: "3"

